apiVersion: v1
kind: Service
metadata:
  name: geolocation-svc
  labels:
      name: geolocation-svc
      app: geolocation
spec:
  selector:
    name: geolocation-svc
   type: NodePort
   ports:
          - port: 80
            targetPort: 8080
            protocol: TCP