apiVersion: v1
kind: Pod
metadata:
 name: geolocation
spec:
 containers:
 - image: omkarshetkar/geolocation:slim
   name: geolocation
   ports:
   - containerPort: 8080
   volumeMounts:
    - mountPath: /opt/packt/geolocation/data
      name: geodata
 volumes:
  - name: geodata
    hostPath:
     path: /opt/packt/geolocation/data

